### ISSUE TITLE
[FEAT] Make additional os/arch binaries available for releases

### ISSUE THREAD

**Issue by joshdk** [mgoltzsche/khelm#23]
> **Is your feature request related to a problem? Please describe.**

There are folks who do development work on a Mac, and not having a prebuild `khelm` binary (`GOOS=darwin GOARCH=amd64`) available results in friction for them when upgrading to a newer release.

Artifacts for the most recent release:
![image](https://user-images.githubusercontent.com/307183/136273959-747cb08b-d13b-48f5-a86a-7123310a9f18.png)

Additionally, the [installation instructions from the readme](https://github.com/mgoltzsche/khelm#plugin-installation) do not currently work.

```shell
$ go get github.com/mgoltzsche/khelm/cmd/khelm
go get: module github.com/mgoltzsche/khelm@upgrade found (v0.9.2), but does not contain package github.com/mgoltzsche/khelm/cmd/khelm

$ go install github.com/mgoltzsche/khelm/cmd/khelm
go install: version is required when current directory is not in a module
	Try 'go install github.com/mgoltzsche/khelm/cmd/khelm@latest' to install the latest version

$ go install github.com/mgoltzsche/khelm/cmd/khelm@latest
go install github.com/mgoltzsche/khelm/cmd/khelm@latest: module github.com/mgoltzsche/khelm@latest found (v0.9.2), but does not contain package github.com/mgoltzsche/khelm/cmd/khelm
```

> **Describe the solution you'd like**

Attach binaries for additional os/arch combinations as release artifacts, so that they can be downloaded and installed just like how Linux users can with the `khelm-linux-amd64` binary. 

> **Describe alternatives you've considered**

You currently need to clone the repo, and run `GOOS=darwin GOARCH=amd64 go build` by hand.

> **Additional context**

The `khelm-linux-amd64` binary is [currently built using a `docker build` followed by a `docker cp`](https://github.com/mgoltzsche/khelm/blob/master/Makefile#L34-L42). Maybe switching to [goreleaser](https://github.com/goreleaser/goreleaser) would make release builds easier to manage?

**Comment by mgoltzsche** [comment]
Oh, I'll try to carve out some time the next days to fix this and finally merge the `v2` branch into master. Also using goreleaser sounds like a good idea.
