### ISSUE TITLE
Support helm 3

### ISSUE THREAD

**Issue by mgoltzsche** [mgoltzsche/khelm#6]
Helm 3 should be supported. However not all Helm 2 charts work with helm 3.
To allow to explicitly declare which helm version should be used to render a chart the plugin version could be used so that `v1` uses helm 2 and `v2` uses helm 3.

**Comment by elmariofredo** [comment]
Hi,

given helm v2 depreciation https://helm.sh/blog/helm-v2-deprecation-timeline/ I would suggest to move fully with helm 3.

Is there anything I can do help you implement it?

**Comment by mgoltzsche** [comment]
@elmariofredo thanks for the link and offer.

I started working on this in #8.

**Comment by mgoltzsche** [comment]
Helm 3 is now supported within the `v2` branch for now.
I am going to move Helm 2 support into a `v1` branch and the `v2` branch into `master` soon.

GitHub workflows are set up and there's a v2.0.0-alpha.1 release: the binary is attached to the release and the container image is hosted on both the DockerHub and GitHub registry. (Though to access the GitHub registry you need to authenticate.)
