### ISSUE TITLE
[QUESTION] Does khelm support exec-style KRM functions?

### ISSUE THREAD

**Issue by allanadair** [mgoltzsche/khelm#61]
Context: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/

I tried to get this to work some weeks ago. I was able to utilize khelm as a containerized KRM function, but when trying to use it as an Exec KRM function, I could not find any obvious way to get it working.

The exec-style KRM function is particularly useful for those who do not have the ability to launch containers when running kustomize, like when using kustomize in ArgoCD.

To provide more context, I author KRM functions for myself and I am able to run them as containerized or exec KRM functions interchangeably.

So, does khelm support exec-style KRM functions? If so, can a working example be provided? And if not, could this feature be added?

**Comment by mgoltzsche** [comment]
@allanadair thanks for creating the issue! I didn't know about that feature within kustomize. It might work with khelm's kpt function support: run the binary `khelmfn` without any arguments/option. If that doesn't work I agree the feature should be added.

**Comment by allanadair** [comment]
Are the release binaries (e.g `khelm-linux-amd64`) the same as the `khelmfn` binary?

**Comment by mgoltzsche** [comment]
Yes, unfortunately, I made khelm run as kpt function when the khelm binary is called `khelmfn` (which is the case within the shipped container image), see [here](https://github.com/mgoltzsche/khelm/blob/b1f1ecfbc1953ef05e8e906303252aa2274a573b/cmd/khelm/root.go#L61) :sweat_smile:. (At least the early kpt interface required me to add implement kpt support within the root command if I remember correctly.)

**Comment by allanadair** [comment]
Ah, this is excellent! Thank you. Renaming the binary to "khelmfn" results in working exec-style KRM functions.
